
server:  port: 8083
  
spring:  application:    name: 'transportador'


eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: https://eureka-server-cadalso.herokuapp.com/eureka